name: Publish Release

on:
  push:
    tags:
      - '*'
    #    branches: [main]
    #schedule:
    # 定时任务，每天 UTC 时间 0 点运行
    #- cron: "0 0 * * *"
  #workflow_dispatch:
permissions: # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests

jobs:
  tags:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 为了 git pull --unshallow，我们需要获取所有的提交历史

      - name: Set up Git user
        run: |
          git config --global user.email "wangfj11@foxmail.com"
          git config --global user.name "AlianBlank"

      - name: change-version-by-tag
        uses: AlianBlank/github-action-tag-version@1.0.0
        with:
          version: ${{ github.ref_name }}
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            branch: ${{ github.head_ref }}
#      - run: echo "version - ${{ steps.info.outputs.currentVersion }}"